export default function(){
return [
        { id: 0, img: "/src/assets/images/golden-temple.jpg",  title: "The Golden Temple", description:"The Golden temple is the holiest shrine of Sikhs. It was built in late 16th century by Guru Arjan, and a copy of the Sikh scripture was placed inside the temple in 1604. Its sanctum walls were covered in marble and the dome was decorated with gold foil by Ranjit Singh in the 19th century.The Harmandir Sahib is an open house of worship for all men and women, from all walks of life and faith. It has a square plan with four entrances, has a circumambulation path around the pool. The temple is a collection of buildings around the sanctum and the pool."},
        { id: 1, img: "/src/assets/images/taj-mahal.jpg",  title: "Taj Mahal",description:"Taj Mahal, one of Seven Wonders of the World is just not known for its pristine beauty but much of its grace lies in the fact that it is a monument dedicated to love. Taj Mahal was built by Mughal Emperor Shah Jahan for his beloved wife Mumtaz Mahal. She died in 1631, while giving birth to their 14th child.The construction of Taj Mahal started in the year 1631 and it took approximately 22 years to build what we see today. An epitome of love, it made use of the services of 22,000 laborers and 1,000 elephants. "},
        { id: 2, img: "/src/assets/images/gatewayOfIndia.jpg",  title: "Gateway Of India",description:"The Gateway of India is an arch monument built during the 20th century in Bombay, India. The monument was erected to commemorate the landing of King George V and Queen Mary at Apollo Bunder on their visit to India in 1911.The structural plan of Gateway of India is designed in the Indo-Saracenic style.The Gateway of India is located on the waterfront at Apollo Bunder area at the end of Chhatrapati Shivaji Marg in South Mumbai and overlooks the Arabian Sea.The monument has also been referred to as the Taj Mahal of Mumbai,[8] and is the city's top tourist attraction."},
        { id: 3, img: "/src/assets/images/jal-mahal.jpg",  title: "Jal Mahal",description:"Jal Mahal (meaning 'Water Palace') is a palace in the middle of the Man Sagar Lake in Jaipur city, the capital of the state of Rajasthan, India. The palace and the lake around it were renovated and enlarged in the 18th century by Maharaja Jai Singh II of Amber.The Jal Mahal palace is an architectural showcase of the Rajput style of architecture on a grand scale.It has a picturesque view of the lake itself but owing to its seclusion from land is equally the focus of a viewpoint from the Man Sagar Dam."},
        { id: 4, img: "/src/assets/images/mysorePalace.jpg",  title: "Mysore Palace",description:"Ambavilas Palace, otherwise known as the Mysore Palace, is a historical palace and a royal residence at Mysore in the southern Karnataka state of India. It is the official residence of the Wadiyar dynasty and the seat of the Kingdom of Mysore. The palace is in the centre of Mysore, and faces the Chamundi Hills eastward.Mysore is commonly described as the 'City of Palaces', and there are seven palaces including this one; however, 'Mysore Palace' refers specifically to this one within the Old Fort.The land on which the palace now stands was originally known as puragiri (literally, citadel), and is now known as the Old Fort."}
    ]
}
